In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df_train = pd.read_csv('training.csv')
df_test = pd.read_csv('unlabeled.csv')

In [21]:
df_train.head()

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.73,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.42,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.95,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.64,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma

In [22]:
df_train.hospital_death.unique()

array([0, 1], dtype=int64)

In [23]:
df_train_one = df_train.loc[:,'encounter_id': 'd1_diasbp_max']
df_train_two = df_train.loc[:, 'd1_diasbp_min': 'd1_albumin_max']
df_train_three = df_train.loc[:, 'd1_albumin_min': 'h1_lactate_max']
df_train_four = df_train.loc[:, 'h1_lactate_min':]

In [24]:
df_train_one.shape

(91713, 49)

In [25]:
round(df_train_one.isna().sum()/len(df_train_one), 1)*100

encounter_id               0.0
patient_id                 0.0
hospital_id                0.0
hospital_death             0.0
age                        0.0
bmi                        0.0
elective_surgery           0.0
ethnicity                  0.0
gender                     0.0
height                     0.0
hospital_admit_source     20.0
icu_admit_source           0.0
icu_id                     0.0
icu_stay_type              0.0
icu_type                   0.0
pre_icu_los_days           0.0
readmission_status         0.0
weight                     0.0
albumin_apache            60.0
apache_2_diagnosis         0.0
apache_3j_diagnosis        0.0
apache_post_operative      0.0
arf_apache                 0.0
bilirubin_apache          60.0
bun_apache                20.0
creatinine_apache         20.0
fio2_apache               80.0
gcs_eyes_apache            0.0
gcs_motor_apache           0.0
gcs_unable_apache          0.0
gcs_verbal_apache          0.0
glucose_apache            10.0
heart_rate_apache          0.0
hematocrit_apache         20.0
intubated_apache           0.0
map_apache                 0.0
paco2_apache              80.0
paco2_for_ph_apache       80.0
pao2_apache               80.0
ph_apache                 80.0
resprate_apache            0.0
sodium_apache             20.0
temp_apache                0.0
urineoutput_apache        50.0
ventilated_apache          0.0
wbc_apache                20.0
d1_diasbp_invasive_max    70.0
d1_diasbp_invasive_min    70.0
d1_diasbp_max              0.0
dtype: float64

In [26]:
round(df_train_two.isna().sum()/len(df_train_two), 1)*100

d1_diasbp_min                 0.0
d1_diasbp_noninvasive_max     0.0
d1_diasbp_noninvasive_min     0.0
d1_heartrate_max              0.0
d1_heartrate_min              0.0
d1_mbp_invasive_max          70.0
d1_mbp_invasive_min          70.0
d1_mbp_max                    0.0
d1_mbp_min                    0.0
d1_mbp_noninvasive_max        0.0
d1_mbp_noninvasive_min        0.0
d1_resprate_max               0.0
d1_resprate_min               0.0
d1_spo2_max                   0.0
d1_spo2_min                   0.0
d1_sysbp_invasive_max        70.0
d1_sysbp_invasive_min        70.0
d1_sysbp_max                  0.0
d1_sysbp_min                  0.0
d1_sysbp_noninvasive_max      0.0
d1_sysbp_noninvasive_min      0.0
d1_temp_max                   0.0
d1_temp_min                   0.0
h1_diasbp_invasive_max       80.0
h1_diasbp_invasive_min       80.0
h1_diasbp_max                 0.0
h1_diasbp_min                 0.0
h1_diasbp_noninvasive_max    10.0
h1_diasbp_noninvasive_min    10.0
h1_heartrate_max              0.0
h1_heartrate_min              0.0
h1_mbp_invasive_max          80.0
h1_mbp_invasive_min          80.0
h1_mbp_max                   10.0
h1_mbp_min                   10.0
h1_mbp_noninvasive_max       10.0
h1_mbp_noninvasive_min       10.0
h1_resprate_max               0.0
h1_resprate_min               0.0
h1_spo2_max                   0.0
h1_spo2_min                   0.0
h1_sysbp_invasive_max        80.0
h1_sysbp_invasive_min        80.0
h1_sysbp_max                  0.0
h1_sysbp_min                  0.0
h1_sysbp_noninvasive_max     10.0
h1_sysbp_noninvasive_min     10.0
h1_temp_max                  20.0
h1_temp_min                  20.0
d1_albumin_max               50.0
dtype: float64

In [27]:
round(df_train_three.isna().sum()/len(df_train_three), 1)*100

d1_albumin_min       50.0
d1_bilirubin_max     60.0
d1_bilirubin_min     60.0
d1_bun_max           10.0
d1_bun_min           10.0
d1_calcium_max       10.0
d1_calcium_min       10.0
d1_creatinine_max    10.0
d1_creatinine_min    10.0
d1_glucose_max       10.0
d1_glucose_min       10.0
d1_hco3_max          20.0
d1_hco3_min          20.0
d1_hemaglobin_max    10.0
d1_hemaglobin_min    10.0
d1_hematocrit_max    10.0
d1_hematocrit_min    10.0
d1_inr_max           60.0
d1_inr_min           60.0
d1_lactate_max       70.0
d1_lactate_min       70.0
d1_platelets_max     10.0
d1_platelets_min     10.0
d1_potassium_max     10.0
d1_potassium_min     10.0
d1_sodium_max        10.0
d1_sodium_min        10.0
d1_wbc_max           10.0
d1_wbc_min           10.0
h1_albumin_max       90.0
h1_albumin_min       90.0
h1_bilirubin_max     90.0
h1_bilirubin_min     90.0
h1_bun_max           80.0
h1_bun_min           80.0
h1_calcium_max       80.0
h1_calcium_min       80.0
h1_creatinine_max    80.0
h1_creatinine_min    80.0
h1_glucose_max       60.0
h1_glucose_min       60.0
h1_hco3_max          80.0
h1_hco3_min          80.0
h1_hemaglobin_max    80.0
h1_hemaglobin_min    80.0
h1_hematocrit_max    80.0
h1_hematocrit_min    80.0
h1_inr_max           60.0
h1_inr_min           60.0
h1_lactate_max       90.0
dtype: float64

In [28]:
df_train['hospital_admit_source'].isna().value_counts()

False    70304
True     21409
Name: hospital_admit_source, dtype: int64

In [29]:
df_train['readmission_status'].value_counts() ## readmission status will be dropped

0    91713
Name: readmission_status, dtype: int64

In [40]:
df_train_one.isna().describe().T

                        count unique    top   freq
encounter_id            91713      1  False  91713
patient_id              91713      1  False  91713
hospital_id             91713      1  False  91713
hospital_death          91713      1  False  91713
age                     91713      2  False  87485
bmi                     91713      2  False  88284
elective_surgery        91713      1  False  91713
ethnicity               91713      2  False  90318
gender                  91713      2  False  91688
height                  91713      2  False  90379
hospital_admit_source   91713      2  False  70304
icu_admit_source        91713      2  False  91601
icu_id                  91713      1  False  91713
icu_stay_type           91713      1  False  91713
icu_type                91713      1  False  91713
pre_icu_los_days        91713      1  False  91713
readmission_status      91713      1  False  91713
weight                  91713      2  False  88993
albumin_apache          91713      2   True  54379
apache_2_diagnosis      91713      2  False  90051
apache_3j_diagnosis     91713      2  False  90612
apache_post_operative   91713      1  False  91713
arf_apache              91713      2  False  90998
bilirubin_apache        91713      2   True  58134
bun_apache              91713      2  False  72451
creatinine_apache       91713      2  False  72860
fio2_apache             91713      2   True  70868
gcs_eyes_apache         91713      2  False  89812
gcs_motor_apache        91713      2  False  89812
gcs_unable_apache       91713      2  False  90676
gcs_verbal_apache       91713      2  False  89812
glucose_apache          91713      2  False  80677
heart_rate_apache       91713      2  False  90835
hematocrit_apache       91713      2  False  71835
intubated_apache        91713      2  False  90998
map_apache              91713      2  False  90719
paco2_apache            91713      2   True  70868
paco2_for_ph_apache     91713      2   True  70868
pao2_apache             91713      2   True  70868
ph_apache               91713      2   True  70868
resprate_apache         91713      2  False  90479
sodium_apache           91713      2  False  73113
temp_apache             91713      2  False  87605
urineoutput_apache      91713      2   True  48998
ventilated_apache       91713      2  False  90998
wbc_apache              91713      2  False  69701
d1_diasbp_invasive_max  91713      2   True  67984
d1_diasbp_invasive_min  91713      2   True  67984
d1_diasbp_max           91713      2  False  91548

In [41]:
numeric_df = df_train._get_numeric_data()
numeric_df_test = df_test._get_numeric_data()

(round(numeric_df.isna().sum()/len(numeric_df), 1)*100).head(50)

encounter_id                 0.0
patient_id                   0.0
hospital_id                  0.0
hospital_death               0.0
age                          0.0
bmi                          0.0
elective_surgery             0.0
height                       0.0
icu_id                       0.0
pre_icu_los_days             0.0
readmission_status           0.0
weight                       0.0
albumin_apache               0.0
apache_2_diagnosis           0.0
apache_3j_diagnosis          0.0
apache_post_operative        0.0
arf_apache                   0.0
bilirubin_apache             0.0
bun_apache                   0.0
creatinine_apache            0.0
fio2_apache                  0.0
gcs_eyes_apache              0.0
gcs_motor_apache             0.0
gcs_unable_apache            0.0
gcs_verbal_apache            0.0
glucose_apache               0.0
heart_rate_apache            0.0
hematocrit_apache            0.0
intubated_apache             0.0
map_apache                   0.0
paco2_apache                 0.0
paco2_for_ph_apache          0.0
pao2_apache                  0.0
ph_apache                    0.0
resprate_apache              0.0
sodium_apache                0.0
temp_apache                  0.0
urineoutput_apache           0.0
ventilated_apache            0.0
wbc_apache                   0.0
d1_diasbp_invasive_max       0.0
d1_diasbp_invasive_min       0.0
d1_diasbp_max                0.0
d1_diasbp_min                0.0
d1_diasbp_noninvasive_max    0.0
d1_diasbp_noninvasive_min    0.0
d1_heartrate_max             0.0
d1_heartrate_min             0.0
d1_mbp_invasive_max          0.0
d1_mbp_invasive_min          0.0
dtype: float64

In [32]:
numeric_df.solid_tumor_with_metastasis.median()

0.0

In [33]:
numeric_df.fillna(-999, inplace = True)

In [42]:
numeric_df_test.fillna(-999, inplace = True)

In [63]:
string_df = df_train.select_dtypes(include = 'object')

In [67]:
string_df_test = df_test.select_dtypes(include = 'object')
string_df_test.fillna('unknown', inplace = True)

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py:4244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs

In [65]:
string_df.fillna(value = 'unknown', inplace = True)

C:\Users\user\Anaconda3\lib\site-packages\pandas\core\frame.py:4244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  **kwargs

In [64]:
string_df.shape

(91713, 8)

In [66]:
string_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91713 entries, 0 to 91712
Data columns (total 8 columns):
ethnicity                91713 non-null object
gender                   91713 non-null object
hospital_admit_source    91713 non-null object
icu_admit_source         91713 non-null object
icu_stay_type            91713 non-null object
icu_type                 91713 non-null object
apache_3j_bodysystem     91713 non-null object
apache_2_bodysystem      91713 non-null object
dtypes: object(8)
memory usage: 5.6+ MB

In [71]:
from sklearn.preprocessing import LabelEncoder

In [75]:
encoder = LabelEncoder()
encode = string_df.apply(encoder.fit_transform)

In [76]:
encode_test = string_df_test.apply(encoder.fit_transform)

In [80]:
train = numeric_df.join(encode)

In [81]:
test = numeric_df_test.join(encode_test)

In [82]:
train.shape, test.shape

((91713, 186), (39308, 186))

In [9]:
data_dict = pd.read_csv('WiDS Datathon 2020 Dictionary.csv')
data_dict.tail(60)

,Category,Variable Name,Unit of Measure,Data Type,Description,Example
128,labs,d1_wbc_min,10^9/L,numeric,The lowest white blood cell count for the pati...,10
129,labs,h1_albumin_max,None,numeric,The lowest albumin concentration of the patien...,30
130,labs,h1_albumin_min,g/L,numeric,The lowest albumin concentration of the patien...,30
131,labs,h1_bilirubin_max,micromol/L,numeric,The highest bilirubin concentration of the pat...,20
132,labs,h1_bilirubin_min,micromol/L,numeric,The lowest bilirubin concentration of the pati...,20
133,labs,h1_bun_max,mmol/L,numeric,The highest blood urea nitrogen concentration ...,5
134,labs,h1_bun_min,mmol/L,numeric,The lowest blood urea nitrogen concentration o...,5
135,labs,h1_calcium_max,mmol/L,numeric,The highest calcium concentration of the patie...,2.5
136,labs,h1_calcium_min,mmol/L,numeric,The lowest calcium concentration of the patien...,2.5
137,labs,h1_creatinine_max,micromol/L,numeric,The highest creatinine concentration of the pa...,70
138,labs,h1_creatinine_min,micromol/L,numeric,The lowest creatinine concentration of the pat...,70
139,labs,h1_glucose_max,mmol/L,numeric,The highest glucose concentration of the patie...,5
140,labs,h1_glucose_min,mmol/L,numeric,The lowest glucose concentration of the patien...,5
141,labs,h1_hco3_max,mmol/L,numeric,The highest bicarbonate concentration for the ...,30
142,labs,h1_hco3_min,None,numeric,The lowest bicarbonate concentration for the p...,30
143,labs,h1_hemaglobin_max,g/dL,numeric,The highest hemoglobin concentration for the p...,10
144,labs,h1_hemaglobin_min,g/dL,numeric,The lowest hemoglobin concentration for the pa...,10
145,labs,h1_hematocrit_max,Fraction,numeric,The highest volume proportion of red blood cel...,0.4
146,labs,h1_hematocrit_min,Fraction,numeric,The lowest volume proportion of red blood cell...,0.4
147,labs,h1_inr_max,micromol/L,numeric,The highest international normalized ratio for...,1
148,labs,h1_inr_min,micromol/L,numeric,The lowest international normalized ratio for ...,1
149,labs,h1_lactate_max,mmol/L,numeric,The highest lactate concentration for the pati...,1
150,labs,h1_lactate_min,mmol/L,numeric,The lowest lactate concentration for the patie...,1
151,labs,h1_platelets_max,10^9/L,numeric,The highest platelet count for the patient dur...,200
152,labs,h1_platelets_min,10^9/L,numeric,The lowest platelet count for the patient duri...,200
153,labs,h1_potassium_max,mmol/L,numeric,The highest potassium concentration for the pa...,3.8
154,labs,h1_potassium_min,mmol/L,numeric,The lowest potassium concentration for the pat...,3.8
155,labs,h1_sodium_max,mmol/L,numeric,The highest sodium concentration for the patie...,145
156,labs,h1_sodium_min,mmol/L,numeric,The lowest sodium concentration for the patien...,145
157,labs,h1_wbc_max,10^9/L,numeric,The highest white blood cell count for the pat...,10
158,labs,h1_wbc_min,10^9/L,numeric,The lowest white blood cell count for the pati...,10
159,labs blood gas,d1_arterial_pco2_max,Millimetres of mercury,numeric,The highest arterial partial pressure of carbo...,40
160,labs blood gas,d1_arterial_pco2_min,Millimetres of mercury,numeric,The lowest arterial partial pressure of carbon...,40
161,labs blood gas,d1_arterial_ph_max,None,numeric,The highest arterial pH for the patient during...,7.4
162,labs blood gas,d1_arterial_ph_min,None,numeric,The lowest arterial pH for the patient during ...,7.4
163,labs blood gas,d1_arterial_po2_max,Millimetres of mercury,numeric,The highest arterial partial pressure of oxyge...,80
164,labs blood gas,d1_arterial_po2_min,Millimetres of mercury,numeric,The lowest arterial partial pressure of oxygen...,80
165,labs blood gas,d1_pao2fio2ratio_max,Fraction,numeric,The highest fraction of inspired oxygen for th...,0.21
166,labs blood gas,d1_pao2fio2ratio_min,Fraction,numeric,The lowest fraction of inspired oxygen for the...,0.21
167,labs blood gas,h1_arterial_pco2_max,Millimetres of mercury,numeric,The highest arterial partial pressure of carbo...,40
168,labs blood gas,h1_arterial_pco2_min,Millimetres of mercury,numeric,The lowest arterial partial pressure of carbon...,40
169,labs blood gas,h1_arterial_ph_max,None,numeric,The highest arterial pH for the patient during...,7.4
170,labs blood gas,h1_arterial_ph_min,None,numeric,The lowest arterial pH for the patient during ...,7.4
171,labs blood gas,h1_arterial_po2_max,Millimetres of mercury,numeric,The highest arterial partial pressure of oxyge...,80
172,labs blood gas,h1_arterial_po2_min,Millimetres of mercury,numeric,The lowest arterial partial pressure of oxygen...,80
173,labs blood gas,h1_pao2fio2ratio_max,Fraction,numeric,The highest fraction of inspired oxygen for th...,0.21
174,labs blood gas,h1_pao2fio2ratio_min,Fraction,numeric,The lowest fraction of inspired oxygen for the...,0.21
175,APACHE prediction,apache_4a_hospital_death_prob,None,numeric,The APACHE IVa probabilistic prediction of in-...,0.31
176,APACHE prediction,apache_4a_icu_death_prob,None,numeric,The APACHE IVa probabilistic prediction of in ...,0.24
177,APACHE comorbidity,aids,None,binary,Whether the patient has a definitive diagnosis...,1
178,APACHE comorbidity,cirrhosis,None,binary,Whether the patient has a history of heavy alc...,1
179,APACHE comorbidity,diabetes_mellitus,None,binary,Whether the patient has been diagnosed with di...,1
180,APACHE comorbidity,hepatic_failure,None,binary,Whether the patient has cirrhosis and addition...,1
181,APACHE comorbidity,immunosuppression,None,binary,Whether the patient has their immune system su...,1
182,APACHE comorbidity,leukemia,None,binary,Whether the patient has been diagnosed with ac...,1
183,APACHE comorbidity,lymphoma,None,binary,Whether the patient has been diagnosed with no...,1
184,APACHE comorbidity,solid_tumor_with_metastasis,None,binary,Whether the patient has been diagnosed with an...,1
185,APACHE grouping,apache_3j_bodysystem,None,string,Admission diagnosis group for APACHE III,Cardiovascular
186,APACHE grouping,apache_2_bodysystem,None,string,Admission diagnosis group for APACHE II,Respiratory
187,GOSSIS example prediction,pred,None,numeric,"Example mortality prediction, shared as a 'bas...",0.000921

In [10]:
solution_template = pd.read_csv('solution_template.csv')
solution_template.head()

   encounter_id  hospital_death
0             2             NaN
1             5             NaN
2             7             NaN
3             8             NaN
4            10             NaN

Let's do Simple lightgbm modelling